config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: 'homes#top'
  get '/home/about' => 'homes#about'
  resources :books, only: [:index, :new, :create, :show, :edit, :update, :destroy, :create] do
   resource :favorites, only: [:create, :destroy]  
   resources :book_comments, only: [:create, :destroy]
end
  resources :users, only: [:index, :create, :show, :edit, :update, :destroy]
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length:{maximum:200}
  
  has_one_attached :profile_image

def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
　　profile_image.variant(resize_to_limit: [width, height]).processed
end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
         
         
 has_many :books, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :book_comments, dependent: :destroy
       validates :name, length:{ in: 2..20 }
       validates :name, uniqueness: true
       validates :email, uniqueness: true
          validates :introduction, length:{maximum: 50 }
         validates :email,presence: true
         validates :password,presence: true,on: :registration
      
         
         
         has_one_attached :profile_image
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully"
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully"
    root_path
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:password])
   
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
   def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end  
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
   @books = Book.all
   @book = Book.new(book_params)
   @book.user_id = current_user.id
     if @book.save
       flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book.id)
     else
       render :index
       
     end
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book)
    else
     render :edit
   end   
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end



  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
   private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def index
    @users = User.all
    @user = User.find_by(params[:id])
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
     flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
   else
     render :edit
   end   
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= flash[:notice] %>
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<div class="container-lg d-flex justify-content-center">

<%= form_with model: @book do |f| %>
<h2 class="row">Editing Book</h2>
<p class="mb-0 row"><label>Title</label></p>
<div class="row">
  <%= f.text_field :title,class:"col-12" %>
  </div>
<div class="mb-0 row"><label>Opinion</label></div>
<div class="row"><%= f.text_area :body,class:"col-12" %></div>
<div class="row "><%= f.submit "Update Book",class:"btn-success" %></div>
<div class="row"><span><%= link_to "Show|", book_path(@book) %></span>
<span><%= link_to " Back", books_path %></span></div>
<% end %>

</div>

app/views/books/index.html.erb
<div class="container">  <!-- この行を追加 -->
  <div class="row">      <!-- この行を追加 -->
  <div class="col-md-3" style="background-color: white;">
    
  <% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>User info</h1>

<table class="table table-Hoverable">
<% if current_user.profile_image.attached? %>
<p class="mb-0"><%= image_tag current_user.get_profile_image(100, 100) %></p>
<% else %>
    <%= image_tag 'sample-author1.jpg', size: "200x200" %>
<% end %>

 <tr>
   <td>name</td>
   <td><%= current_user.name %></td>
 </tr>

 <tr>
   <td>introduction</td>
   <td><%= current_user.introduction %></td>
 </tr>
</table>


   <%= link_to edit_user_path(current_user.id), class: "btn btn-light btn-outline-secondary btn-block w-75", method: :get do %>
   <i class="fas fa-user-cog"></i>
   <% end %>


<%= form_with model: @book do |f| %>
<h2>New book</h2>
  <p><label for="inputTitle">Title</label></p>
  <%= f.text_field :title %>
  <p><label for="inputOpinion">Opinion</label></p>
  <p><%= f.text_area :body %></p>
  <%= f.submit "Create Book",class:"btn-success" %>
  <% end %>
  
    
    </div>
    <div class="col-md-8 offset-md-1">
      
<h2>Books</h2>
<table class="table table-Hoverable">
  <th></th>
  <th>Title</th>
<th>Opinion</th>
<th></th>
<% @books.each do |book| %>
  <tr>
  <td class="profile_image"><%= link_to user_path(book.user.id) do %>
  <%= image_tag book.user.get_profile_image(100, 100) %>
  <% end %>
  </td>
  
  <td class="title"><%= link_to "#{book.title}", book_path(book.id) %></td>
  
  <td class="body"><%= book.body %></td>
  
  <td><% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book.id), method: :delete do %>
        <i class="fas fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(book.id), method: :post do %>
        <i class="fas fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </p>
  <% end %>
  </td>
  
  <td><p><%= "コメント数: #{book.book_comments.count}" %></p></td>
  
  </span>
  </tr>
  <% end %>
  </table>

</div>
</div>  <!-- この行を追加 -->
</div>  

app/views/books/show.html.erb
<%= flash[:notice] %>

<div class="container">  <!-- この行を追加 -->
  <div class="row">      <!-- この行を追加 -->
  <div class="col-md-3" style="background-color: white;">
    
    
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>User info</h1>

<table class="table table-Hoverable">
<% if current_user.profile_image.attached? %>
<p class="mb-0"><%= image_tag @book.user.get_profile_image(100, 100) %></p>
<% else %>
    <%= image_tag 'sample-author1.jpg', size: "200x200" %>
<% end %>

 <tr>
   <td>name</td>
   <td><%= @book.user.name %></td>
 </tr>

 <tr>
   <td>introduction</td>
   <td><%= @book.user.introduction %></td>
 </tr>
</table>


   <% if @book.user.id==current_user.id %>
   <%= link_to edit_user_path(current_user.id), class: "btn btn-light btn-outline-secondary btn-block w-75", method: :get do %>
   <i class="fas fa-user-cog"></i>
   <% end %>
<% else %>
<%= link_to edit_user_path(@book.user.id), class: "btn btn-light btn-outline-secondary btn-block w-75", method: :get do %>
   <i class="fas fa-user-cog"></i>
<% end %>
<% end %>
 


<%= form_with model: Book.new do |f| %>
<h2>New book</h2>
  <p><label for="inputTitle">Title</label></p>
  <%= f.text_field :title %>
  <p><label for="inputOpinion">Opinion</label></p>
  <p><%= f.text_area :body %></p>
  <%= f.submit "Create Book",class:"btn-success" %>
  <% end %>



 </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-Hoverable">

  <tr>
  <td class="profile_image">
    <%= link_to user_path(@book.user.id) do%>
    <%= image_tag @book.user.get_profile_image(100,100) %>
    <% end %>
  <p><%= link_to "#{@book.user.name}", user_path(@book.user.id) %> </p>
  </td>
  
  <td class="name"><%= link_to "#{@book.title}" %> </td>
  <td class="name"><%= @book.body %></td>
  
  <td><% if @book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(@book), method: :delete do %>
        <i class="fas fa-heart"></i><%= @book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(@book), method: :post do %>
        <i class="fas fa-heart"></i><%= @book.favorites.count %>
      <% end %>
    </p>
  <% end %>
  </td>
  
  <td><p><%= "コメント数: #{@book.book_comments.count}" %></p></td>
  
  <% if @book.user.id == current_user.id %>
  <td class="link"><span><%= link_to "Edit", edit_book_path(@book),class:"btn btn-success" %></span></td>
   <td class="link"><span><%= link_to "Destroy", book_path(@book), method: :delete,class:"btn btn-danger" %></span></td>
   <% else %>
   <td></td>
   <td></td>
   <% end %>
  </tr>
  </table>
  
  <div>
  <% @book.book_comments.each do |book_comment| %>
<p>
    <%= image_tag book_comment.user.get_profile_image(100,100) %>
    <%= book_comment.comment %>
    <% if book_comment.user == current_user %>
      <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete,class:"btn btn-danger" %>
    <% end %>
</p>
<%= book_comment.user.name %>
  <% end %>
</div>

<div>
  <%= form_with model: [@book, @book_comment] do |f| %>
    <p><%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %></p>
    <%= f.submit "送信する" %>
  <% end %>
</div>

</div>
</div>  <!-- この行を追加 -->
</div>    <!-- この

app/views/homes/about.html.erb
<div class="container">
<h1 class="text-center">Welcome to <span><i class="fas fa-book"></i></span>Bookers!</h1>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<div class="container">
 <div class="d-flex flex-column">
 <div class="row">
<h1 class="offset-3 col-lg-5">welcome to <p class="fas fa-book"></p>Bookers !!</h1>
</div>
<div class="row">
<span class="offset-3 col-lg-4">In&nbsp;<p class="fas fa-book"></p>Bookers,</span>
</div>
<div class="row">
<p class="col-lg-6 mx-auto">you can share and exchange your opinions, inpressions, and emotions<br>about various books!</p>
</div>
<div class="row">
<div class="col-lg-5 mx-auto mb-3">
        <%= link_to "Log in", new_user_session_path, class: "btn-sm btn-info btn-block d-flex align-items-center justify-content-center text-decoration-none" %>
      </div>
       </div>
      <div class="row">
       <div class="col-lg-5 mx-auto">
        <%= link_to "Sign up", new_user_registration_path, class: "btn-sm btn-success btn-block d-flex align-items-center justify-content-center text-decoration-none" %>
      </div>
      </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1">-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <script src="https://kit.fontawesome.com/a61de98c96.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-secondary list-unstyled">
      
      <li class="nav-item ml-3">
        <%= link_to "Bookers", root_path, class: 'nav-link text-white' %>
      </li>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav4">
    <% if user_signed_in? %>
    <i class="fas fa-home"></i><li class="nav-item">
        <%= link_to "Home", user_path(current_user.id), class: 'nav-link text-white' %>
      </li>
    <i class="fas fa-users"></i><li class="nav-item">
        <%= link_to "Users", users_path, class: 'nav-link text-white' %>
      </li>
      <i class="fas fa-book-open"></i><li class="nav-item">
        <%= link_to "Books", books_path, class: 'nav-link text-white' %>
      </li>
      <i class="fas fa-sign-out-alt"></i><li class="nav-item">
        <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
      </li>
    <% else %>
    <i class="fas fa-home"></i></i><li class="nav-item">
        <%= link_to "Home", root_path, class: 'nav-link text-white' %>
      </li>
      <i class="fas fa-link"></i><li class="nav-item">
        <%= link_to "About", '/home/about', class: 'nav-link text-white' %>
      </li>
      <i class="fas fa-user-plus"></i><li class="nav-item">
        <%= link_to "sign up", new_user_registration_path, class: 'nav-link text-white' %>
      </li>
      <i class="fas fa-sign-in-alt"></i><li class="nav-item">
        <%= link_to "login", new_user_session_path, class: 'nav-link text-white' %>
      </li>
 
    <% end %>
       </div>
    </nav>
  </header>
  
    <%= yield %>
    <footer>
   <div class="d-flex justify-content-center mt-5">CopyRight Infratop.inc</div>
  </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %> error prohted this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container-lg d-flex justify-content-center">

<%= form_with model: @user do |f| %>
<h2 class="row">User info</h2>
   <div class="row"><label for="inputName">Name</label></div>
  <div class="row"><%= f.text_field :name %></div>
  <div class="row"><label for="inputImage">Image</label></div>
  <div class="row"><%= f.file_field :profile_image,  accept: "image/*" %></div>
  <div class="row"><label for="inputIntroduction">Introduction</label></div>
  <div class="row"><%= f.text_area :introduction %></div>
  
  <div class="row"><%= f.submit "Update User",class:"btn-secondary" %></div>
<% end %>
</div>

app/views/users/index.html.erb
  <div class="container">  <!-- この行を追加 -->
  <div class="row">      <!-- この行を追加 -->
  <div class="col-md-3" style="background-color: white;">
    
      <% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>User info</h1>

<table class="table table-Hoverable">
<% if current_user.profile_image.attached? %>
<p class="mb-0"><%= image_tag current_user.get_profile_image(100, 100) %></p>
<% else %>
    <%= image_tag 'sample-author1.jpg', size: "200x200" %>
<% end %>

 <tr>
   <td>name</td>
   <td><%= current_user.name %></td>
 </tr>

 <tr>
   <td>introduction</td>
   <td><%= current_user.introduction %></td>
 </tr>
</table>


   <%= link_to edit_user_path(current_user.id), class: "btn btn-light btn-outline-secondary btn-block w-75", method: :get do %>
   <i class="fas fa-user-cog"></i>
   <% end %>


<%= form_with model: Book.new do |f| %>
<h2>New book</h2>
  <p><label for="inputTitle">Title</label></p>
  <%= f.text_field :title %>
  <p><label for="inputOpinion">Opinion</label></p>
  <p><%= f.text_area :body %></p>
  <%= f.submit "Create Book",class:"btn-success" %>
  <% end %>
  
      
      
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-Hoverable">
    <th>image</th>
    <th>name</th>
    <th></th>
<% @users.each do |user| %>

  <tr>
  <td class="profile_image"><%= image_tag user.get_profile_image(100,100), accept:"image/*" %></td>
 
  <td class="name"><%= user.name %></td>
  
  <td class="link">
   <%= link_to "Show", user_path(user.id) %>
   </td>
  </tr>
<% end %>
  </table>
</div>
</div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>
<div class="container">
  <div class="row">
  <div class="col-md-3" style="background-color: white;">
    
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>User info</h1>

<table class="table table-Hoverable">
<% if current_user.profile_image.attached? %>
<p class="mb-0"><%= image_tag @user.get_profile_image(100, 100) %></p>
<% else %>
    <%= image_tag 'sample-author1.jpg', size: "200x200" %>
<% end %>

 <tr>
   <td>name</td>
   <td><%= @user.name %></td>
 </tr>

 <tr>
   <td>introduction</td>
   <td><%= @user.introduction %></td>
 </tr>
 
</table>

<% if @user.id==current_user.id %>
   <%= link_to edit_user_path(current_user.id), class: "btn btn-light btn-outline-secondary btn-block w-75", method: :get do %>
   <i class="fas fa-user-cog"></i>
   <% end %>
<% else %>
<%= link_to edit_user_path(@user.id), class: "btn btn-light btn-outline-secondary btn-block w-75", method: :get do %>
   <i class="fas fa-user-cog"></i>
<% end %>
<% end %>



<%= form_with model: Book.new do |f| %>
<h2>New book</h2>
  <p><label for="inputTitle">Title</label></p>
  <%= f.text_field :title %>
  <p><label for="inputOpinion">Opinion</label></p>
  <p><%= f.text_area :body %></p>
  <%= f.submit "Create Book",class:"btn-success" %>
  <% end %>

    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
<table class="table table-Hoverable">
  <th></th>
  <th>Title</th>
<th>Opinion</th>
<th></th>
    <% @user.books.each do |book| %>
    <tr>

  <td class="profile_image"><%= link_to user_path(@user) do %>
  <%= image_tag @user.get_profile_image(100, 100) %>
  <% end %>
  </td>

  <td class="title"><%= link_to "#{book.title}", book_path(book.id) %></td>
  
  <td class="body"><%= book.body %></td>
  
  <td><% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book.id), method: :delete do %>
        <i class="fas fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(book.id), method: :post do %>
        <i class="fas fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </p>
  <% end %>
  </td>
  
  <td><p><%= "コメント数: #{book.book_comments.count}" %></p></td>
  

  </span>
  </tr>
<% end %>
  </table>



</div>
</div>
</div>